# Generated by Django 3.2.8 on 2021-10-16 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='Курс')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего редактирования')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': '2. Курсы',
                'ordering': ('course_name',),
            },
        ),
        migrations.CreateModel(
            name='SubdivisionCadet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision_name', models.CharField(max_length=255, verbose_name='Подразделение')),
                ('subdivision_short_name', models.CharField(max_length=255, verbose_name='Короткое название подразделения (только заглавные английские буквы)')),
                ('last_modified', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последнего редактирования')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто может вносить изменения')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': '1. Факультеты',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, verbose_name='Группа')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего редактирования')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='covid_kadet_old.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': '3. Группы',
                'ordering': ('group_name',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeCadet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('year_of_entering', models.IntegerField(blank=True, null=True, verbose_name='Год поступления')),
                ('covid_1_date', models.DateField(blank=True, null=True, verbose_name='Дата первой прививки')),
                ('covid_2_date', models.DateField(blank=True, null=True, verbose_name='Дата второй прививки')),
                ('is_willing', models.BooleanField(default=False, verbose_name='Желает пройти вакцинацию')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего редактирования')),
                ('group_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='covid_kadet_old.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Курсант',
                'verbose_name_plural': '4. Курсанты',
                'ordering': ('last_name',),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='covid_kadet_old.subdivisioncadet', verbose_name='Факультет'),
        ),
    ]
