# Generated by Django 3.1.5 on 2021-10-14 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего редактирования')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('last_name',),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='VaccineKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30, verbose_name='Вид вакцины')),
            ],
            options={
                'verbose_name': 'Вид вакцины',
                'verbose_name_plural': 'Виды вакцины',
                'ordering': ('kind',),
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения вакцинации')),
                ('order', models.IntegerField(choices=[(1, 'Первая'), (2, 'Вторая')], verbose_name='Очередность вакцины')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.employee', verbose_name='Сотрудник')),
                ('vaccine_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.vaccinekind', verbose_name='Вид вакцины')),
            ],
            options={
                'verbose_name': 'Вакцинация',
                'verbose_name_plural': 'Вакцинации',
                'ordering': ('employee',),
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision_name', models.CharField(max_length=255, verbose_name='Подразделение')),
                ('subdivision_short_name', models.CharField(max_length=255, verbose_name='Короткое название подразделения (только заглавные английские буквы)')),
                ('last_modified', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последнего редактирования')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто может вносить изменения')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ('subdivision_name',),
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='covid.position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='employee',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='covid.subdivision', verbose_name='Подразделение'),
        ),
    ]
