# Generated by Django 3.1.5 on 2021-10-14 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=50, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Звание',
                'verbose_name_plural': 'Звания',
                'ordering': ('rank',),
            },
        ),
        migrations.AlterModelOptions(
            name='vaccination',
            options={'ordering': ('-date',), 'verbose_name': 'Вакцинация', 'verbose_name_plural': 'Вакцинации'},
        ),
        migrations.AddField(
            model_name='employee',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, 'Мужской'), (2, 'Женский')], null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='employee',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='covid.rank', verbose_name='Звание'),
        ),
    ]
