# Generated by Django 3.1.5 on 2021-10-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccinecourse',
            options={'ordering': ('id',), 'verbose_name': 'Курс вакцинации', 'verbose_name_plural': 'Курсы вакцинации'},
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='vaccinekind',
            name='one_component',
            field=models.BooleanField(default=False, verbose_name='Является однокомпонентной'),
        ),
    ]
