# Generated by Django 3.2.8 on 2021-10-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20211015_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contraindications_explain',
            field=models.TextField(blank=True, null=True, verbose_name='Пояснение к противопоказаниям'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерти'),
        ),
        migrations.AddField(
            model_name='employee',
            name='has_contraindications',
            field=models.BooleanField(default=False, verbose_name='Имеет противопоказания к прививке'),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Холостой/Не замужем'), (2, 'Разведен/Разведена'), (3, 'Вдова/Вдовец')], null=True, verbose_name='Семейное положение'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_status',
            field=models.IntegerField(choices=[(1, 'Работает'), (2, 'Уволен')], default=1, verbose_name='Рабочий статус'),
        ),
    ]
