# Generated by Django 3.2.8 on 2021-10-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_auto_20211016_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Холостой/Не замужем'), (2, 'Женат/Замужем'), (3, 'Разведен/Разведена'), (4, 'Вдова/Вдовец')], null=True, verbose_name='Семейное положение'),
        ),
    ]
