# Generated by Django 3.2.8 on 2021-10-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_alter_employee_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecourse',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего редактирования'),
        ),
    ]
