# Generated by Django 3.2.8 on 2021-10-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_vaccinecourse_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_willing',
            field=models.BooleanField(default=False, verbose_name='Желает пройти вакцинацию'),
        ),
    ]
