# Generated by Django 3.2.8 on 2021-10-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_cadet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeecadet',
            options={'ordering': ('last_name',), 'verbose_name': 'Курсант', 'verbose_name_plural': '4. Курсанты'},
        ),
    ]
