# Generated by Django 3.1.5 on 2021-10-14 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=255, verbose_name='Болезнь')),
            ],
            options={
                'verbose_name': 'Болезнь',
                'verbose_name_plural': 'Болезни',
                'ordering': ('disease_name',),
            },
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ('employee',), 'verbose_name': 'Больничный/карантин', 'verbose_name_plural': 'Больничные/карантины'},
        ),
        migrations.AddField(
            model_name='disease',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disease.diseasename', verbose_name='Болезнь'),
        ),
    ]
